FROM --platform=linux/amd64 ghcr.io/usace-cloud-compute/cc-tiledb-python:latest

RUN apt-get update && apt-get install -y libgfortran5

COPY src src
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD [src/plugin.py]